const errors = {
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_ERROR: 'LOGIN_ERROR',
  USER_INFO_NOT_FOUND: 'USER_INFO_NOT_FOUND',
  GET_USER_INFO_ERROR: 'GET_USER_INFO_ERROR',
  NUTRITION_NOT_FOUND: 'NUTRITION_NOT_FOUND',
  REQUEST_NUTRITION_ERROR: 'REQUEST_NUTRITION_ERROR',
  FOOD_NOT_FOUND: 'FOOD_NOT_FOUND',
  REQUEST_FOOD_ERROR: 'REQUEST_FOOD_ERROR',
  ADD_MEAL_FAILED: 'ADD_MEAL_FAILED',
  ADD_MEAL_ERROR: 'ADD_MEAL_ERROR',
};

export default errors;
